export declare const TYPES: readonly ["primary", "secondary", "outline"];
export type Type = (typeof TYPES)[number];
export declare const SIZES: readonly ["s", "m", "l", "xl"];
export type Size = (typeof SIZES)[number];
export declare const SHAPES: readonly ["default", "round", "circle", "square"];
export type Shape = (typeof SHAPES)[number];
export declare const STATUS: readonly ["success", "warning", "danger", "primary"];
export type Status = (typeof STATUS)[number];
export declare const MESSAGETYPE: readonly ["success", "warning", "error", "primary", "loading"];
export type MessageType = (typeof MESSAGETYPE)[number];
export declare const NOTIFICATIONTYPE: readonly ["primary", "success", "warning", "error"];
export type NotificationType = (typeof NOTIFICATIONTYPE)[number];
export declare const SKIN: readonly ["auto", "light", "dark"];
export type Skin = (typeof SKIN)[number];
export declare const TITLETYPE: readonly ["success", "warning", "danger", "primary", "secondary", "default"];
export type TitleType = (typeof TITLETYPE)[number];
export declare const TEXTTYPE: readonly ["success", "warning", "danger", "primary", "secondary", "default", "third", "disabled"];
export type TextType = (typeof TEXTTYPE)[number];
export declare const DIRECTION: readonly ["vertical", "horizontal"];
export type Direction = (typeof DIRECTION)[number];
export type AnimationType = 'upward' | 'fade';
